###GET TASKS

GET http://localhost:8000/api/tasks

###GET A SINGLE TASK

GET http://localhost:8000/api/tasks/614d3fa9154c06c7b2b12a97

###POST TASK
POST http://localhost:8000/api/tasks/create
Content-Type: application/json

{
  "user": "Joacos",
  "title" : "Read a good book 3",
  "date" : "2021-09-22",
  "description": "About Nfts"
}

###PUT TASK

PUT http://localhost:8000/api/tasks/update/614d3fa9154c06c7b2b12a97
Content-Type: application/json

{
  "title" : "Write a complete fullstack app",
  "date": "2021-09-22T00:00:00.000Z",
  "description": "Do my last coding dojo asigment"
}


###DELETE TASKS
DELETE http://localhost:8000/api/tasks/delete/61e1cbd29da0838c09d163f6
